[project]
name = "02-fly-in"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.13.5",
    "pygame>=2.6.1",
]

[project.scripts]
02-fly-in = "02_fly_in:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
